# Generated by Django 3.2.7 on 2021-09-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_expense_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='color',
        ),
    ]
