# Generated by Django 3.2.6 on 2021-08-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_expense_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='percent',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='percentage amount'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Amount'),
        ),
    ]
